FROM node:10.15

RUN \
    apt-get update && apt-get install -y --no-install-recommends apt-utils \
    python-dev \
    python-pip \
    ssh && \
    pip install --upgrade setuptools && \
    pip install -q awscli && \
    apt-get -y purge python-dev && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND teletype
